### ISSUE TITLE
🤖 [FEATURE] domain url 변경

### ISSUE THREAD

**Issue by DongGeon0908** [YAPP-Github/oksusu-susu-api#7]
# 🤖 기능 개요

**AS-IS**
> https://oksusu.site/~

**TO-BE**
> https://api.oksusu.site/~

### ✅ Implement TODO

- [x] domain prefix 추가 

### 🚧 작업 브랜치

imp/domain-prefix

**Comment by DongGeon0908** [comment]
domain 붙인 것을 그대로 이용하기 보다는, api를 붙이는게 좋을 것 같아요!
추가적으로, 도메인 구입 비용 및 aws 정상 비용 올려주시면 감사하겠습니다 :)

**Comment by wjdtkdgns** [comment]
바꿨습니다~~
비용 정산은 나중에 할게요! 수업 들어가야 해서요 ㅎㅎ...

**Comment by DongGeon0908** [comment]
나이스입니다~
